[package]
name = "bloom-derivation"
version = "1.0.0"
edition = "2021"
rust-version = "1.80.0"

[lib]
proc-macro = true

[dependencies]
bloom-offchain = { version = "1.0.0", path = "../bloom-offchain" }
syn = "2.0.38"
quote = "1.0.33"
derive_utils = "0.13.2"
num-rational = "0.4.1"