name: TEST CI for Develop Branch

# Trigger the workflow on push to the develop branch
on:
  push:
    branches:
      - cicdtest  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-
          
    - name: Run cargo fmt check
      id: cargo_fmt
      run: |
        cargo fmt --all --check

    - name: Build bloom-cardano-agent
      id: cargo_build
      run: |
        cargo build --package bloom-cardano-agent --bin bloom-cardano-agent
        echo "cargo_build_result=$?" >> $GITHUB_ENV

    - name: Send result to Slack
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL2 }}
        FMT_STATUS: ${{ steps.cargo_fmt.outcome }}
        BUILD_STATUS: ${{ steps.cargo_build.outcome }}
      with:
        payload: |
          {
            "text": "Cargo fmt and build check result. See details at ${{ github.run_url }}",
            "attachments": [
              {
                "text": "Cargo fmt check finished with status: ${{ env.FMT_STATUS }}.",
                "color": "${{ env.FMT_STATUS == 'success' && 'good' || '#FF0000' }}"
              },
              {
                "text": "Cargo build finished with status: ${{ env.BUILD_STATUS }}.",
                "color": "${{ env.BUILD_STATUS == 'success' && 'good' || '#FF0000' }}"
              }
            ]
          }
